var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/users/route.js")
R.c("server/chunks/node_modules_ff20b4e0._.js")
R.c("server/chunks/node_modules_next_66de1ce2._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_a97713e8._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_df9a87ed._.js")
R.c("server/chunks/node_modules_a2fccba5._.js")
R.c("server/chunks/[root-of-the-server]__fa802a2c._.js")
R.c("server/chunks/_next-internal_server_app_api_users_route_actions_4b9121e3.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/users/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/users/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
