var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/lineups/route.js")
R.c("server/chunks/node_modules_648a038f._.js")
R.c("server/chunks/node_modules_next_7f12805d._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_a97713e8._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_df9a87ed._.js")
R.c("server/chunks/node_modules_ed3b37be._.js")
R.c("server/chunks/[root-of-the-server]__6ece9db9._.js")
R.c("server/chunks/_next-internal_server_app_api_lineups_route_actions_2b3c6e43.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/lineups/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/lineups/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
