var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/leagues/[id]/combined-schedule/route.js")
R.c("server/chunks/node_modules_e52aa080._.js")
R.c("server/chunks/node_modules_next_86113685._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_6d68d473._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_ef23ed2a._.js")
R.c("server/chunks/[root-of-the-server]__109f3ec4._.js")
R.c("server/chunks/ce889_server_app_api_leagues_[id]_combined-schedule_route_actions_506ef227.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/leagues/[id]/combined-schedule/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/leagues/[id]/combined-schedule/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
