var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/manager/leagues/route.js")
R.c("server/chunks/node_modules_7722f88b._.js")
R.c("server/chunks/node_modules_next_c272e536._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_e1d63bee._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_df9a87ed._.js")
R.c("server/chunks/node_modules_3f400348._.js")
R.c("server/chunks/[root-of-the-server]__679ab0f5._.js")
R.c("server/chunks/_next-internal_server_app_api_manager_leagues_route_actions_bf5375ce.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/manager/leagues/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/manager/leagues/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
