var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/players/draft/route.js")
R.c("server/chunks/node_modules_d69f1da7._.js")
R.c("server/chunks/node_modules_next_586e84c7._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_a97713e8._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_df9a87ed._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_xlsx_xlsx_mjs_539ebb60._.js")
R.c("server/chunks/node_modules_8768de88._.js")
R.c("server/chunks/[root-of-the-server]__0d29bbf6._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_players_draft_route_actions_2f0c6011.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/admin/players/draft/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/admin/players/draft/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
