var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/leagues/[id]/gameweeks/[gameweekId]/route.js")
R.c("server/chunks/node_modules_a319ddc6._.js")
R.c("server/chunks/node_modules_next_4b485ce7._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_3e86ea90._.js")
R.c("server/chunks/node_modules_f1080bde._.js")
R.c("server/chunks/[root-of-the-server]__ae8ab55d._.js")
R.c("server/chunks/ce889_server_app_api_leagues_[id]_gameweeks_[gameweekId]_route_actions_1263a461.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/leagues/[id]/gameweeks/[gameweekId]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/leagues/[id]/gameweeks/[gameweekId]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
