var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/leagues/[id]/lineups/route.js")
R.c("server/chunks/node_modules_6574c3c1._.js")
R.c("server/chunks/node_modules_next_9d2b1a32._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_80b78522._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_b0ef4d74._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_207db2ad._.js")
R.c("server/chunks/[root-of-the-server]__b6d76878._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_leagues_[id]_lineups_route_actions_1936af1c.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/admin/leagues/[id]/lineups/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/admin/leagues/[id]/lineups/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
