// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/admin" | "/dashboard/admin/gameweeks" | "/dashboard/admin/leagues" | "/dashboard/admin/leagues/[id]" | "/dashboard/admin/leagues/[id]/cup" | "/dashboard/admin/leagues/[id]/cup-lineups" | "/dashboard/admin/leagues/[id]/cup/groups" | "/dashboard/admin/leagues/[id]/cup/knockout-draw" | "/dashboard/admin/leagues/[id]/cup/schedule" | "/dashboard/admin/leagues/[id]/cup/standings" | "/dashboard/admin/leagues/[id]/gameweeks" | "/dashboard/admin/leagues/[id]/lineups" | "/dashboard/admin/leagues/[id]/managers" | "/dashboard/admin/leagues/[id]/players" | "/dashboard/admin/leagues/[id]/players/draft" | "/dashboard/admin/leagues/[id]/players/import" | "/dashboard/admin/leagues/[id]/results" | "/dashboard/admin/leagues/[id]/settings" | "/dashboard/admin/leagues/[id]/standings" | "/dashboard/admin/leagues/new" | "/dashboard/admin/migration" | "/dashboard/admin/migration/sql" | "/dashboard/admin/players" | "/dashboard/admin/players/import" | "/dashboard/admin/results" | "/dashboard/admin/schedule-generator" | "/dashboard/admin/squads" | "/dashboard/admin/table" | "/dashboard/admin/users" | "/dashboard/create-league" | "/dashboard/leagues/[id]" | "/dashboard/leagues/[id]/cup/results" | "/dashboard/leagues/[id]/cup/standings" | "/dashboard/leagues/[id]/default-lineup" | "/dashboard/leagues/[id]/results" | "/dashboard/leagues/[id]/schedule" | "/dashboard/leagues/[id]/settings" | "/dashboard/leagues/[id]/squad" | "/dashboard/leagues/[id]/standings" | "/dashboard/leagues/[id]/tablica" | "/dashboard/leagues/[id]/top-scorers" | "/dashboard/results" | "/dashboard/squad" | "/dashboard/standings" | "/setup-admin" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]" | "/style-guide" | "/test-gameweeks"
type AppRouteHandlerRoutes = "/api/admin/complete-gameweeks" | "/api/admin/cups/[id]/[cupId]/knockout-draw" | "/api/admin/cups/[id]/knockout-draw" | "/api/admin/cups/[id]/lineups" | "/api/admin/cups/[id]/resolve-placeholders" | "/api/admin/leagues/[id]/export" | "/api/admin/leagues/[id]/lineups" | "/api/admin/migrate" | "/api/admin/migrate-names" | "/api/admin/migration/import" | "/api/admin/migration/sql" | "/api/admin/migration/template" | "/api/admin/migration/verify" | "/api/admin/players/draft" | "/api/admin/players/import" | "/api/admin/set-admin" | "/api/admin/stats" | "/api/cron/apply-default-lineups" | "/api/cron/complete-gameweeks" | "/api/cup-lineups" | "/api/cups" | "/api/cups/[id]/advance" | "/api/cups/[id]/gameweeks" | "/api/cups/[id]/group-standings" | "/api/cups/[id]/groups" | "/api/cups/[id]/manual-tiebreakers" | "/api/cups/[id]/qualified-teams" | "/api/cups/[id]/results" | "/api/cups/[id]/schedule" | "/api/default-cup-lineups" | "/api/default-lineups" | "/api/gameweeks" | "/api/gameweeks/[id]" | "/api/gameweeks/[id]/lineups" | "/api/gameweeks/[id]/matches-with-lineups" | "/api/leagues" | "/api/leagues/[id]" | "/api/leagues/[id]/combined-schedule" | "/api/leagues/[id]/cup/top-scorers" | "/api/leagues/[id]/gameweeks" | "/api/leagues/[id]/gameweeks/[gameweekId]" | "/api/leagues/[id]/managers" | "/api/leagues/[id]/manual-tiebreakers" | "/api/leagues/[id]/matches" | "/api/leagues/[id]/players" | "/api/leagues/[id]/posts" | "/api/leagues/[id]/results" | "/api/leagues/[id]/schedule" | "/api/leagues/[id]/standings" | "/api/leagues/[id]/top-scorers" | "/api/lineups" | "/api/lineups/validate-dual" | "/api/manager/leagues" | "/api/manager/leagues/[id]/performance" | "/api/manager/leagues/[id]/squad" | "/api/manager/leagues/[id]/squad-info" | "/api/players" | "/api/players/[id]" | "/api/posts/[id]" | "/api/results" | "/api/results/[id]" | "/api/squads/[id]/team-name" | "/api/test" | "/api/user/role" | "/api/users" | "/api/users/[id]" | "/api/webhooks/clerk"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard/admin" | "/dashboard/admin/leagues/[id]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/complete-gameweeks": {}
  "/api/admin/cups/[id]/[cupId]/knockout-draw": { "id": string; "cupId": string; }
  "/api/admin/cups/[id]/knockout-draw": { "id": string; }
  "/api/admin/cups/[id]/lineups": { "id": string; }
  "/api/admin/cups/[id]/resolve-placeholders": { "id": string; }
  "/api/admin/leagues/[id]/export": { "id": string; }
  "/api/admin/leagues/[id]/lineups": { "id": string; }
  "/api/admin/migrate": {}
  "/api/admin/migrate-names": {}
  "/api/admin/migration/import": {}
  "/api/admin/migration/sql": {}
  "/api/admin/migration/template": {}
  "/api/admin/migration/verify": {}
  "/api/admin/players/draft": {}
  "/api/admin/players/import": {}
  "/api/admin/set-admin": {}
  "/api/admin/stats": {}
  "/api/cron/apply-default-lineups": {}
  "/api/cron/complete-gameweeks": {}
  "/api/cup-lineups": {}
  "/api/cups": {}
  "/api/cups/[id]/advance": { "id": string; }
  "/api/cups/[id]/gameweeks": { "id": string; }
  "/api/cups/[id]/group-standings": { "id": string; }
  "/api/cups/[id]/groups": { "id": string; }
  "/api/cups/[id]/manual-tiebreakers": { "id": string; }
  "/api/cups/[id]/qualified-teams": { "id": string; }
  "/api/cups/[id]/results": { "id": string; }
  "/api/cups/[id]/schedule": { "id": string; }
  "/api/default-cup-lineups": {}
  "/api/default-lineups": {}
  "/api/gameweeks": {}
  "/api/gameweeks/[id]": { "id": string; }
  "/api/gameweeks/[id]/lineups": { "id": string; }
  "/api/gameweeks/[id]/matches-with-lineups": { "id": string; }
  "/api/leagues": {}
  "/api/leagues/[id]": { "id": string; }
  "/api/leagues/[id]/combined-schedule": { "id": string; }
  "/api/leagues/[id]/cup/top-scorers": { "id": string; }
  "/api/leagues/[id]/gameweeks": { "id": string; }
  "/api/leagues/[id]/gameweeks/[gameweekId]": { "id": string; "gameweekId": string; }
  "/api/leagues/[id]/managers": { "id": string; }
  "/api/leagues/[id]/manual-tiebreakers": { "id": string; }
  "/api/leagues/[id]/matches": { "id": string; }
  "/api/leagues/[id]/players": { "id": string; }
  "/api/leagues/[id]/posts": { "id": string; }
  "/api/leagues/[id]/results": { "id": string; }
  "/api/leagues/[id]/schedule": { "id": string; }
  "/api/leagues/[id]/standings": { "id": string; }
  "/api/leagues/[id]/top-scorers": { "id": string; }
  "/api/lineups": {}
  "/api/lineups/validate-dual": {}
  "/api/manager/leagues": {}
  "/api/manager/leagues/[id]/performance": { "id": string; }
  "/api/manager/leagues/[id]/squad": { "id": string; }
  "/api/manager/leagues/[id]/squad-info": { "id": string; }
  "/api/players": {}
  "/api/players/[id]": { "id": string; }
  "/api/posts/[id]": { "id": string; }
  "/api/results": {}
  "/api/results/[id]": { "id": string; }
  "/api/squads/[id]/team-name": { "id": string; }
  "/api/test": {}
  "/api/user/role": {}
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/api/webhooks/clerk": {}
  "/dashboard": {}
  "/dashboard/admin": {}
  "/dashboard/admin/gameweeks": {}
  "/dashboard/admin/leagues": {}
  "/dashboard/admin/leagues/[id]": { "id": string; }
  "/dashboard/admin/leagues/[id]/cup": { "id": string; }
  "/dashboard/admin/leagues/[id]/cup-lineups": { "id": string; }
  "/dashboard/admin/leagues/[id]/cup/groups": { "id": string; }
  "/dashboard/admin/leagues/[id]/cup/knockout-draw": { "id": string; }
  "/dashboard/admin/leagues/[id]/cup/schedule": { "id": string; }
  "/dashboard/admin/leagues/[id]/cup/standings": { "id": string; }
  "/dashboard/admin/leagues/[id]/gameweeks": { "id": string; }
  "/dashboard/admin/leagues/[id]/lineups": { "id": string; }
  "/dashboard/admin/leagues/[id]/managers": { "id": string; }
  "/dashboard/admin/leagues/[id]/players": { "id": string; }
  "/dashboard/admin/leagues/[id]/players/draft": { "id": string; }
  "/dashboard/admin/leagues/[id]/players/import": { "id": string; }
  "/dashboard/admin/leagues/[id]/results": { "id": string; }
  "/dashboard/admin/leagues/[id]/settings": { "id": string; }
  "/dashboard/admin/leagues/[id]/standings": { "id": string; }
  "/dashboard/admin/leagues/new": {}
  "/dashboard/admin/migration": {}
  "/dashboard/admin/migration/sql": {}
  "/dashboard/admin/players": {}
  "/dashboard/admin/players/import": {}
  "/dashboard/admin/results": {}
  "/dashboard/admin/schedule-generator": {}
  "/dashboard/admin/squads": {}
  "/dashboard/admin/table": {}
  "/dashboard/admin/users": {}
  "/dashboard/create-league": {}
  "/dashboard/leagues/[id]": { "id": string; }
  "/dashboard/leagues/[id]/cup/results": { "id": string; }
  "/dashboard/leagues/[id]/cup/standings": { "id": string; }
  "/dashboard/leagues/[id]/default-lineup": { "id": string; }
  "/dashboard/leagues/[id]/results": { "id": string; }
  "/dashboard/leagues/[id]/schedule": { "id": string; }
  "/dashboard/leagues/[id]/settings": { "id": string; }
  "/dashboard/leagues/[id]/squad": { "id": string; }
  "/dashboard/leagues/[id]/standings": { "id": string; }
  "/dashboard/leagues/[id]/tablica": { "id": string; }
  "/dashboard/leagues/[id]/top-scorers": { "id": string; }
  "/dashboard/results": {}
  "/dashboard/squad": {}
  "/dashboard/standings": {}
  "/setup-admin": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
  "/style-guide": {}
  "/test-gameweeks": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard/admin": never
  "/dashboard/admin/leagues/[id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
