// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/dashboard/admin/gameweeks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/gameweeks">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/gameweeks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/cup-lineups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/cup-lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/cup-lineups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/cup/groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/cup/groups">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/cup/groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/cup/knockout-draw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/cup/knockout-draw">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/cup/knockout-draw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/cup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/cup">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/cup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/cup/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/cup/schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/cup/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/cup/standings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/cup/standings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/cup/standings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/gameweeks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/gameweeks">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/gameweeks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/lineups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/lineups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/managers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/managers">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/managers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/players/draft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/players/draft">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/players/draft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/players/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/players/import">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/players/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/players/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/players">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/players/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/results">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/standings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/[id]/standings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/standings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues/new">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/leagues">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/migration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/migration">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/migration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/migration/sql/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/migration/sql">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/migration/sql/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/players/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/players/import">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/players/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/players/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/players">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/players/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/results">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/schedule-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/schedule-generator">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/schedule-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/squads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/squads">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/squads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/table">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/create-league/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/create-league">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/create-league/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/cup/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]/cup/results">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/cup/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/cup/standings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]/cup/standings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/cup/standings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/default-lineup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]/default-lineup">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/default-lineup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]/results">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]/schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/squad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]/squad">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/squad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/standings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]/standings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/standings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/tablica/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]/tablica">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/tablica/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leagues/[id]/top-scorers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leagues/[id]/top-scorers">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leagues/[id]/top-scorers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/results">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/squad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/squad">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/squad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/standings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/standings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/standings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/setup-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/setup-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sign-in/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../../src/app/sign-in/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sign-up/[[...sign-up]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/[[...sign-up]]">> = Specific
  const handler = {} as typeof import("../../../src/app/sign-up/[[...sign-up]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/style-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/style-guide">> = Specific
  const handler = {} as typeof import("../../../src/app/style-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-gameweeks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-gameweeks">> = Specific
  const handler = {} as typeof import("../../../src/app/test-gameweeks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/complete-gameweeks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/complete-gameweeks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/complete-gameweeks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/cups/[id]/[cupId]/knockout-draw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cups/[id]/[cupId]/knockout-draw">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/cups/[id]/[cupId]/knockout-draw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/cups/[id]/knockout-draw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cups/[id]/knockout-draw">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/cups/[id]/knockout-draw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/cups/[id]/lineups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cups/[id]/lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/cups/[id]/lineups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/cups/[id]/resolve-placeholders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cups/[id]/resolve-placeholders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/cups/[id]/resolve-placeholders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/leagues/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/leagues/[id]/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/leagues/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/leagues/[id]/lineups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/leagues/[id]/lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/leagues/[id]/lineups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/migrate-names/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migrate-names">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/migrate-names/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/migrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migrate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/migrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/migration/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migration/import">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/migration/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/migration/sql/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migration/sql">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/migration/sql/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/migration/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migration/template">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/migration/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/migration/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migration/verify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/migration/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/players/draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/players/draft">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/players/draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/players/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/players/import">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/players/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/set-admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/set-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/set-admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/apply-default-lineups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/apply-default-lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/apply-default-lineups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/complete-gameweeks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/complete-gameweeks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/complete-gameweeks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cup-lineups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cup-lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cup-lineups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cups/[id]/advance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cups/[id]/advance">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cups/[id]/advance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cups/[id]/gameweeks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cups/[id]/gameweeks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cups/[id]/gameweeks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cups/[id]/group-standings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cups/[id]/group-standings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cups/[id]/group-standings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cups/[id]/groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cups/[id]/groups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cups/[id]/groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cups/[id]/manual-tiebreakers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cups/[id]/manual-tiebreakers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cups/[id]/manual-tiebreakers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cups/[id]/qualified-teams/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cups/[id]/qualified-teams">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cups/[id]/qualified-teams/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cups/[id]/results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cups/[id]/results">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cups/[id]/results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cups/[id]/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cups/[id]/schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cups/[id]/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/default-cup-lineups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/default-cup-lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/default-cup-lineups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/default-lineups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/default-lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/default-lineups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/gameweeks/[id]/lineups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gameweeks/[id]/lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/gameweeks/[id]/lineups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/gameweeks/[id]/matches-with-lineups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gameweeks/[id]/matches-with-lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/gameweeks/[id]/matches-with-lineups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/gameweeks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gameweeks/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/gameweeks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/gameweeks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gameweeks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/gameweeks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/combined-schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/combined-schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/combined-schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/cup/top-scorers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/cup/top-scorers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/cup/top-scorers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/gameweeks/[gameweekId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/gameweeks/[gameweekId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/gameweeks/[gameweekId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/gameweeks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/gameweeks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/gameweeks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/managers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/managers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/managers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/manual-tiebreakers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/manual-tiebreakers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/manual-tiebreakers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/matches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/matches">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/matches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/players/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/players">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/players/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/posts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/results">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/standings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/standings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/standings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/[id]/top-scorers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues/[id]/top-scorers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/[id]/top-scorers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/leagues/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leagues">> = Specific
  const handler = {} as typeof import("../../../src/app/api/leagues/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lineups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lineups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lineups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lineups/validate-dual/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lineups/validate-dual">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lineups/validate-dual/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/manager/leagues/[id]/performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/leagues/[id]/performance">> = Specific
  const handler = {} as typeof import("../../../src/app/api/manager/leagues/[id]/performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/manager/leagues/[id]/squad-info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/leagues/[id]/squad-info">> = Specific
  const handler = {} as typeof import("../../../src/app/api/manager/leagues/[id]/squad-info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/manager/leagues/[id]/squad/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/leagues/[id]/squad">> = Specific
  const handler = {} as typeof import("../../../src/app/api/manager/leagues/[id]/squad/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/manager/leagues/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manager/leagues">> = Specific
  const handler = {} as typeof import("../../../src/app/api/manager/leagues/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/players/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/players/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/players/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/players/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/players">> = Specific
  const handler = {} as typeof import("../../../src/app/api/players/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/results/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/results/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/results/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/results">> = Specific
  const handler = {} as typeof import("../../../src/app/api/results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/squads/[id]/team-name/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/squads/[id]/team-name">> = Specific
  const handler = {} as typeof import("../../../src/app/api/squads/[id]/team-name/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test">> = Specific
  const handler = {} as typeof import("../../../src/app/api/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/role">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/clerk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/clerk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/clerk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/dashboard/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/admin/leagues/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/admin/leagues/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/admin/leagues/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
