var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/manager/leagues/[id]/squad-info/route.js")
R.c("server/chunks/node_modules_0605fde4._.js")
R.c("server/chunks/node_modules_next_ec41fbb6._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_3e86ea90._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/node_modules_38502b90._.js")
R.c("server/chunks/[root-of-the-server]__84e1d25f._.js")
R.c("server/chunks/ce889_server_app_api_manager_leagues_[id]_squad-info_route_actions_e9fd2278.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/manager/leagues/[id]/squad-info/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/manager/leagues/[id]/squad-info/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
